version: "3"

services:

  mercure:
    image:  dunglas/mercure
    container_name: mercure
    networks:
      - traefik
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-to-https.redirectScheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectScheme.permanent=true"
      - "traefik.http.routers.mercure.rule=Host(`${MERCURE_DOMAIN}`) || Host(`mercure.traefik`)"
      - "traefik.http.routers.mercure.entryPoints=web"
      - "traefik.http.routers.mercure-https.rule=Host(`${MERCURE_DOMAIN}`) || Host(`mercure.traefik`)"
      - "traefik.http.routers.mercure-https.entryPoints=websecure"
      - "traefik.http.routers.mercure-https.tls=true"
      - "traefik.http.routers.mercure-https.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.routers.mercure-https.tls.domains[0].main=${MERCURE_DOMAIN}"

    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    environment:
      SERVER_NAME:  ":80"
      MERCURE_PUBLISHER_JWT_KEY: "${MERCURE_PUBLISHER_JWT_KEY}"
      MERCURE_SUBSCRIBER_JWT_KEY: "${MERCURE_SUBSCRIBER_JWT_KEY}"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

networks:
  traefik:
    external:
      name: traefik
